/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Bluesky.Client;
using Bluesky.Model;

namespace Bluesky.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IComAtprotoIdentityApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Describe the credentials that should be included in the DID doc of an account that is migrating to this service.
        /// </remarks>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ComAtprotoIdentityGetRecommendedDidCredentials200Response</returns>
        ComAtprotoIdentityGetRecommendedDidCredentials200Response ComAtprotoIdentityGetRecommendedDidCredentials();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Describe the credentials that should be included in the DID doc of an account that is migrating to this service.
        /// </remarks>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ComAtprotoIdentityGetRecommendedDidCredentials200Response</returns>
        ApiResponse<ComAtprotoIdentityGetRecommendedDidCredentials200Response> ComAtprotoIdentityGetRecommendedDidCredentialsWithHttpInfo();
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Request an email with a code to in order to request a signed PLC operation. Requires Auth.
        /// </remarks>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns></returns>
        void ComAtprotoIdentityRequestPlcOperationSignature();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Request an email with a code to in order to request a signed PLC operation. Requires Auth.
        /// </remarks>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ComAtprotoIdentityRequestPlcOperationSignatureWithHttpInfo();
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Resolves a handle (domain name) to a DID.
        /// </remarks>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="handle">The handle to resolve.</param>
        /// <returns>ComAtprotoAdminDeleteAccountRequest</returns>
        ComAtprotoAdminDeleteAccountRequest ComAtprotoIdentityResolveHandle(string handle);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Resolves a handle (domain name) to a DID.
        /// </remarks>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="handle">The handle to resolve.</param>
        /// <returns>ApiResponse of ComAtprotoAdminDeleteAccountRequest</returns>
        ApiResponse<ComAtprotoAdminDeleteAccountRequest> ComAtprotoIdentityResolveHandleWithHttpInfo(string handle);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Signs a PLC operation to update some value(s) in the requesting DID&#39;s document.
        /// </remarks>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="comAtprotoIdentitySignPlcOperationRequest"></param>
        /// <returns>ComAtprotoIdentitySignPlcOperation200Response</returns>
        ComAtprotoIdentitySignPlcOperation200Response ComAtprotoIdentitySignPlcOperation(ComAtprotoIdentitySignPlcOperationRequest comAtprotoIdentitySignPlcOperationRequest);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Signs a PLC operation to update some value(s) in the requesting DID&#39;s document.
        /// </remarks>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="comAtprotoIdentitySignPlcOperationRequest"></param>
        /// <returns>ApiResponse of ComAtprotoIdentitySignPlcOperation200Response</returns>
        ApiResponse<ComAtprotoIdentitySignPlcOperation200Response> ComAtprotoIdentitySignPlcOperationWithHttpInfo(ComAtprotoIdentitySignPlcOperationRequest comAtprotoIdentitySignPlcOperationRequest);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Validates a PLC operation to ensure that it doesn&#39;t violate a service&#39;s constraints or get the identity into a bad state, then submits it to the PLC registry
        /// </remarks>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="comAtprotoIdentitySignPlcOperation200Response"></param>
        /// <returns></returns>
        void ComAtprotoIdentitySubmitPlcOperation(ComAtprotoIdentitySignPlcOperation200Response comAtprotoIdentitySignPlcOperation200Response);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Validates a PLC operation to ensure that it doesn&#39;t violate a service&#39;s constraints or get the identity into a bad state, then submits it to the PLC registry
        /// </remarks>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="comAtprotoIdentitySignPlcOperation200Response"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ComAtprotoIdentitySubmitPlcOperationWithHttpInfo(ComAtprotoIdentitySignPlcOperation200Response comAtprotoIdentitySignPlcOperation200Response);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Updates the current account&#39;s handle. Verifies handle validity, and updates did:plc document if necessary. Implemented by PDS, and requires auth.
        /// </remarks>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="comAtprotoIdentityUpdateHandleRequest"></param>
        /// <returns></returns>
        void ComAtprotoIdentityUpdateHandle(ComAtprotoIdentityUpdateHandleRequest comAtprotoIdentityUpdateHandleRequest);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Updates the current account&#39;s handle. Verifies handle validity, and updates did:plc document if necessary. Implemented by PDS, and requires auth.
        /// </remarks>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="comAtprotoIdentityUpdateHandleRequest"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ComAtprotoIdentityUpdateHandleWithHttpInfo(ComAtprotoIdentityUpdateHandleRequest comAtprotoIdentityUpdateHandleRequest);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IComAtprotoIdentityApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Describe the credentials that should be included in the DID doc of an account that is migrating to this service.
        /// </remarks>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ComAtprotoIdentityGetRecommendedDidCredentials200Response</returns>
        System.Threading.Tasks.Task<ComAtprotoIdentityGetRecommendedDidCredentials200Response> ComAtprotoIdentityGetRecommendedDidCredentialsAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Describe the credentials that should be included in the DID doc of an account that is migrating to this service.
        /// </remarks>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ComAtprotoIdentityGetRecommendedDidCredentials200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<ComAtprotoIdentityGetRecommendedDidCredentials200Response>> ComAtprotoIdentityGetRecommendedDidCredentialsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Request an email with a code to in order to request a signed PLC operation. Requires Auth.
        /// </remarks>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ComAtprotoIdentityRequestPlcOperationSignatureAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Request an email with a code to in order to request a signed PLC operation. Requires Auth.
        /// </remarks>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ComAtprotoIdentityRequestPlcOperationSignatureWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Resolves a handle (domain name) to a DID.
        /// </remarks>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="handle">The handle to resolve.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ComAtprotoAdminDeleteAccountRequest</returns>
        System.Threading.Tasks.Task<ComAtprotoAdminDeleteAccountRequest> ComAtprotoIdentityResolveHandleAsync(string handle, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Resolves a handle (domain name) to a DID.
        /// </remarks>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="handle">The handle to resolve.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ComAtprotoAdminDeleteAccountRequest)</returns>
        System.Threading.Tasks.Task<ApiResponse<ComAtprotoAdminDeleteAccountRequest>> ComAtprotoIdentityResolveHandleWithHttpInfoAsync(string handle, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Signs a PLC operation to update some value(s) in the requesting DID&#39;s document.
        /// </remarks>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="comAtprotoIdentitySignPlcOperationRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ComAtprotoIdentitySignPlcOperation200Response</returns>
        System.Threading.Tasks.Task<ComAtprotoIdentitySignPlcOperation200Response> ComAtprotoIdentitySignPlcOperationAsync(ComAtprotoIdentitySignPlcOperationRequest comAtprotoIdentitySignPlcOperationRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Signs a PLC operation to update some value(s) in the requesting DID&#39;s document.
        /// </remarks>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="comAtprotoIdentitySignPlcOperationRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ComAtprotoIdentitySignPlcOperation200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<ComAtprotoIdentitySignPlcOperation200Response>> ComAtprotoIdentitySignPlcOperationWithHttpInfoAsync(ComAtprotoIdentitySignPlcOperationRequest comAtprotoIdentitySignPlcOperationRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Validates a PLC operation to ensure that it doesn&#39;t violate a service&#39;s constraints or get the identity into a bad state, then submits it to the PLC registry
        /// </remarks>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="comAtprotoIdentitySignPlcOperation200Response"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ComAtprotoIdentitySubmitPlcOperationAsync(ComAtprotoIdentitySignPlcOperation200Response comAtprotoIdentitySignPlcOperation200Response, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Validates a PLC operation to ensure that it doesn&#39;t violate a service&#39;s constraints or get the identity into a bad state, then submits it to the PLC registry
        /// </remarks>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="comAtprotoIdentitySignPlcOperation200Response"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ComAtprotoIdentitySubmitPlcOperationWithHttpInfoAsync(ComAtprotoIdentitySignPlcOperation200Response comAtprotoIdentitySignPlcOperation200Response, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Updates the current account&#39;s handle. Verifies handle validity, and updates did:plc document if necessary. Implemented by PDS, and requires auth.
        /// </remarks>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="comAtprotoIdentityUpdateHandleRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ComAtprotoIdentityUpdateHandleAsync(ComAtprotoIdentityUpdateHandleRequest comAtprotoIdentityUpdateHandleRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Updates the current account&#39;s handle. Verifies handle validity, and updates did:plc document if necessary. Implemented by PDS, and requires auth.
        /// </remarks>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="comAtprotoIdentityUpdateHandleRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ComAtprotoIdentityUpdateHandleWithHttpInfoAsync(ComAtprotoIdentityUpdateHandleRequest comAtprotoIdentityUpdateHandleRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IComAtprotoIdentityApi : IComAtprotoIdentityApiSync, IComAtprotoIdentityApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ComAtprotoIdentityApi : IDisposable, IComAtprotoIdentityApi
    {
        private Bluesky.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ComAtprotoIdentityApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public ComAtprotoIdentityApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ComAtprotoIdentityApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public ComAtprotoIdentityApi(string basePath)
        {
            this.Configuration = Bluesky.Client.Configuration.MergeConfigurations(
                Bluesky.Client.GlobalConfiguration.Instance,
                new Bluesky.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Bluesky.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Bluesky.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ComAtprotoIdentityApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public ComAtprotoIdentityApi(Bluesky.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Bluesky.Client.Configuration.MergeConfigurations(
                Bluesky.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Bluesky.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Bluesky.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ComAtprotoIdentityApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public ComAtprotoIdentityApi(Bluesky.Client.ISynchronousClient client, Bluesky.Client.IAsynchronousClient asyncClient, Bluesky.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Bluesky.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Bluesky.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Bluesky.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Bluesky.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Bluesky.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Bluesky.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  Describe the credentials that should be included in the DID doc of an account that is migrating to this service.
        /// </summary>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ComAtprotoIdentityGetRecommendedDidCredentials200Response</returns>
        public ComAtprotoIdentityGetRecommendedDidCredentials200Response ComAtprotoIdentityGetRecommendedDidCredentials()
        {
            Bluesky.Client.ApiResponse<ComAtprotoIdentityGetRecommendedDidCredentials200Response> localVarResponse = ComAtprotoIdentityGetRecommendedDidCredentialsWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Describe the credentials that should be included in the DID doc of an account that is migrating to this service.
        /// </summary>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ComAtprotoIdentityGetRecommendedDidCredentials200Response</returns>
        public Bluesky.Client.ApiResponse<ComAtprotoIdentityGetRecommendedDidCredentials200Response> ComAtprotoIdentityGetRecommendedDidCredentialsWithHttpInfo()
        {
            Bluesky.Client.RequestOptions localVarRequestOptions = new Bluesky.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Bluesky.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Bluesky.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request
            var localVarResponse = this.Client.Get<ComAtprotoIdentityGetRecommendedDidCredentials200Response>("/com.atproto.identity.getRecommendedDidCredentials", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ComAtprotoIdentityGetRecommendedDidCredentials", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Describe the credentials that should be included in the DID doc of an account that is migrating to this service.
        /// </summary>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ComAtprotoIdentityGetRecommendedDidCredentials200Response</returns>
        public async System.Threading.Tasks.Task<ComAtprotoIdentityGetRecommendedDidCredentials200Response> ComAtprotoIdentityGetRecommendedDidCredentialsAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            var task = ComAtprotoIdentityGetRecommendedDidCredentialsWithHttpInfoAsync(cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            Bluesky.Client.ApiResponse<ComAtprotoIdentityGetRecommendedDidCredentials200Response> localVarResponse = await task.ConfigureAwait(false);
#else
            Bluesky.Client.ApiResponse<ComAtprotoIdentityGetRecommendedDidCredentials200Response> localVarResponse = await task;
#endif
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Describe the credentials that should be included in the DID doc of an account that is migrating to this service.
        /// </summary>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ComAtprotoIdentityGetRecommendedDidCredentials200Response)</returns>
        public async System.Threading.Tasks.Task<Bluesky.Client.ApiResponse<ComAtprotoIdentityGetRecommendedDidCredentials200Response>> ComAtprotoIdentityGetRecommendedDidCredentialsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Bluesky.Client.RequestOptions localVarRequestOptions = new Bluesky.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Bluesky.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Bluesky.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request

            var task = this.AsynchronousClient.GetAsync<ComAtprotoIdentityGetRecommendedDidCredentials200Response>("/com.atproto.identity.getRecommendedDidCredentials", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ComAtprotoIdentityGetRecommendedDidCredentials", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Request an email with a code to in order to request a signed PLC operation. Requires Auth.
        /// </summary>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns></returns>
        public void ComAtprotoIdentityRequestPlcOperationSignature()
        {
            ComAtprotoIdentityRequestPlcOperationSignatureWithHttpInfo();
        }

        /// <summary>
        ///  Request an email with a code to in order to request a signed PLC operation. Requires Auth.
        /// </summary>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object(void)</returns>
        public Bluesky.Client.ApiResponse<Object> ComAtprotoIdentityRequestPlcOperationSignatureWithHttpInfo()
        {
            Bluesky.Client.RequestOptions localVarRequestOptions = new Bluesky.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Bluesky.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Bluesky.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/com.atproto.identity.requestPlcOperationSignature", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ComAtprotoIdentityRequestPlcOperationSignature", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Request an email with a code to in order to request a signed PLC operation. Requires Auth.
        /// </summary>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ComAtprotoIdentityRequestPlcOperationSignatureAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            var task = ComAtprotoIdentityRequestPlcOperationSignatureWithHttpInfoAsync(cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            await task.ConfigureAwait(false);
#else
            await task;
#endif
        }

        /// <summary>
        ///  Request an email with a code to in order to request a signed PLC operation. Requires Auth.
        /// </summary>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Bluesky.Client.ApiResponse<Object>> ComAtprotoIdentityRequestPlcOperationSignatureWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Bluesky.Client.RequestOptions localVarRequestOptions = new Bluesky.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Bluesky.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Bluesky.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var task = this.AsynchronousClient.PostAsync<Object>("/com.atproto.identity.requestPlcOperationSignature", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ComAtprotoIdentityRequestPlcOperationSignature", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Resolves a handle (domain name) to a DID.
        /// </summary>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="handle">The handle to resolve.</param>
        /// <returns>ComAtprotoAdminDeleteAccountRequest</returns>
        public ComAtprotoAdminDeleteAccountRequest ComAtprotoIdentityResolveHandle(string handle)
        {
            Bluesky.Client.ApiResponse<ComAtprotoAdminDeleteAccountRequest> localVarResponse = ComAtprotoIdentityResolveHandleWithHttpInfo(handle);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Resolves a handle (domain name) to a DID.
        /// </summary>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="handle">The handle to resolve.</param>
        /// <returns>ApiResponse of ComAtprotoAdminDeleteAccountRequest</returns>
        public Bluesky.Client.ApiResponse<ComAtprotoAdminDeleteAccountRequest> ComAtprotoIdentityResolveHandleWithHttpInfo(string handle)
        {
            // verify the required parameter 'handle' is set
            if (handle == null)
                throw new Bluesky.Client.ApiException(400, "Missing required parameter 'handle' when calling ComAtprotoIdentityApi->ComAtprotoIdentityResolveHandle");

            Bluesky.Client.RequestOptions localVarRequestOptions = new Bluesky.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Bluesky.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Bluesky.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(Bluesky.Client.ClientUtils.ParameterToMultiMap("", "handle", handle));


            // make the HTTP request
            var localVarResponse = this.Client.Get<ComAtprotoAdminDeleteAccountRequest>("/com.atproto.identity.resolveHandle", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ComAtprotoIdentityResolveHandle", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Resolves a handle (domain name) to a DID.
        /// </summary>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="handle">The handle to resolve.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ComAtprotoAdminDeleteAccountRequest</returns>
        public async System.Threading.Tasks.Task<ComAtprotoAdminDeleteAccountRequest> ComAtprotoIdentityResolveHandleAsync(string handle, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            var task = ComAtprotoIdentityResolveHandleWithHttpInfoAsync(handle, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            Bluesky.Client.ApiResponse<ComAtprotoAdminDeleteAccountRequest> localVarResponse = await task.ConfigureAwait(false);
#else
            Bluesky.Client.ApiResponse<ComAtprotoAdminDeleteAccountRequest> localVarResponse = await task;
#endif
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Resolves a handle (domain name) to a DID.
        /// </summary>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="handle">The handle to resolve.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ComAtprotoAdminDeleteAccountRequest)</returns>
        public async System.Threading.Tasks.Task<Bluesky.Client.ApiResponse<ComAtprotoAdminDeleteAccountRequest>> ComAtprotoIdentityResolveHandleWithHttpInfoAsync(string handle, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'handle' is set
            if (handle == null)
                throw new Bluesky.Client.ApiException(400, "Missing required parameter 'handle' when calling ComAtprotoIdentityApi->ComAtprotoIdentityResolveHandle");


            Bluesky.Client.RequestOptions localVarRequestOptions = new Bluesky.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Bluesky.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Bluesky.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(Bluesky.Client.ClientUtils.ParameterToMultiMap("", "handle", handle));


            // make the HTTP request

            var task = this.AsynchronousClient.GetAsync<ComAtprotoAdminDeleteAccountRequest>("/com.atproto.identity.resolveHandle", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ComAtprotoIdentityResolveHandle", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Signs a PLC operation to update some value(s) in the requesting DID&#39;s document.
        /// </summary>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="comAtprotoIdentitySignPlcOperationRequest"></param>
        /// <returns>ComAtprotoIdentitySignPlcOperation200Response</returns>
        public ComAtprotoIdentitySignPlcOperation200Response ComAtprotoIdentitySignPlcOperation(ComAtprotoIdentitySignPlcOperationRequest comAtprotoIdentitySignPlcOperationRequest)
        {
            Bluesky.Client.ApiResponse<ComAtprotoIdentitySignPlcOperation200Response> localVarResponse = ComAtprotoIdentitySignPlcOperationWithHttpInfo(comAtprotoIdentitySignPlcOperationRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Signs a PLC operation to update some value(s) in the requesting DID&#39;s document.
        /// </summary>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="comAtprotoIdentitySignPlcOperationRequest"></param>
        /// <returns>ApiResponse of ComAtprotoIdentitySignPlcOperation200Response</returns>
        public Bluesky.Client.ApiResponse<ComAtprotoIdentitySignPlcOperation200Response> ComAtprotoIdentitySignPlcOperationWithHttpInfo(ComAtprotoIdentitySignPlcOperationRequest comAtprotoIdentitySignPlcOperationRequest)
        {
            // verify the required parameter 'comAtprotoIdentitySignPlcOperationRequest' is set
            if (comAtprotoIdentitySignPlcOperationRequest == null)
                throw new Bluesky.Client.ApiException(400, "Missing required parameter 'comAtprotoIdentitySignPlcOperationRequest' when calling ComAtprotoIdentityApi->ComAtprotoIdentitySignPlcOperation");

            Bluesky.Client.RequestOptions localVarRequestOptions = new Bluesky.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Bluesky.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Bluesky.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = comAtprotoIdentitySignPlcOperationRequest;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<ComAtprotoIdentitySignPlcOperation200Response>("/com.atproto.identity.signPlcOperation", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ComAtprotoIdentitySignPlcOperation", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Signs a PLC operation to update some value(s) in the requesting DID&#39;s document.
        /// </summary>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="comAtprotoIdentitySignPlcOperationRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ComAtprotoIdentitySignPlcOperation200Response</returns>
        public async System.Threading.Tasks.Task<ComAtprotoIdentitySignPlcOperation200Response> ComAtprotoIdentitySignPlcOperationAsync(ComAtprotoIdentitySignPlcOperationRequest comAtprotoIdentitySignPlcOperationRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            var task = ComAtprotoIdentitySignPlcOperationWithHttpInfoAsync(comAtprotoIdentitySignPlcOperationRequest, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            Bluesky.Client.ApiResponse<ComAtprotoIdentitySignPlcOperation200Response> localVarResponse = await task.ConfigureAwait(false);
#else
            Bluesky.Client.ApiResponse<ComAtprotoIdentitySignPlcOperation200Response> localVarResponse = await task;
#endif
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Signs a PLC operation to update some value(s) in the requesting DID&#39;s document.
        /// </summary>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="comAtprotoIdentitySignPlcOperationRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ComAtprotoIdentitySignPlcOperation200Response)</returns>
        public async System.Threading.Tasks.Task<Bluesky.Client.ApiResponse<ComAtprotoIdentitySignPlcOperation200Response>> ComAtprotoIdentitySignPlcOperationWithHttpInfoAsync(ComAtprotoIdentitySignPlcOperationRequest comAtprotoIdentitySignPlcOperationRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'comAtprotoIdentitySignPlcOperationRequest' is set
            if (comAtprotoIdentitySignPlcOperationRequest == null)
                throw new Bluesky.Client.ApiException(400, "Missing required parameter 'comAtprotoIdentitySignPlcOperationRequest' when calling ComAtprotoIdentityApi->ComAtprotoIdentitySignPlcOperation");


            Bluesky.Client.RequestOptions localVarRequestOptions = new Bluesky.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Bluesky.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Bluesky.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = comAtprotoIdentitySignPlcOperationRequest;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var task = this.AsynchronousClient.PostAsync<ComAtprotoIdentitySignPlcOperation200Response>("/com.atproto.identity.signPlcOperation", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ComAtprotoIdentitySignPlcOperation", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Validates a PLC operation to ensure that it doesn&#39;t violate a service&#39;s constraints or get the identity into a bad state, then submits it to the PLC registry
        /// </summary>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="comAtprotoIdentitySignPlcOperation200Response"></param>
        /// <returns></returns>
        public void ComAtprotoIdentitySubmitPlcOperation(ComAtprotoIdentitySignPlcOperation200Response comAtprotoIdentitySignPlcOperation200Response)
        {
            ComAtprotoIdentitySubmitPlcOperationWithHttpInfo(comAtprotoIdentitySignPlcOperation200Response);
        }

        /// <summary>
        ///  Validates a PLC operation to ensure that it doesn&#39;t violate a service&#39;s constraints or get the identity into a bad state, then submits it to the PLC registry
        /// </summary>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="comAtprotoIdentitySignPlcOperation200Response"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Bluesky.Client.ApiResponse<Object> ComAtprotoIdentitySubmitPlcOperationWithHttpInfo(ComAtprotoIdentitySignPlcOperation200Response comAtprotoIdentitySignPlcOperation200Response)
        {
            // verify the required parameter 'comAtprotoIdentitySignPlcOperation200Response' is set
            if (comAtprotoIdentitySignPlcOperation200Response == null)
                throw new Bluesky.Client.ApiException(400, "Missing required parameter 'comAtprotoIdentitySignPlcOperation200Response' when calling ComAtprotoIdentityApi->ComAtprotoIdentitySubmitPlcOperation");

            Bluesky.Client.RequestOptions localVarRequestOptions = new Bluesky.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Bluesky.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Bluesky.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = comAtprotoIdentitySignPlcOperation200Response;


            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/com.atproto.identity.submitPlcOperation", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ComAtprotoIdentitySubmitPlcOperation", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Validates a PLC operation to ensure that it doesn&#39;t violate a service&#39;s constraints or get the identity into a bad state, then submits it to the PLC registry
        /// </summary>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="comAtprotoIdentitySignPlcOperation200Response"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ComAtprotoIdentitySubmitPlcOperationAsync(ComAtprotoIdentitySignPlcOperation200Response comAtprotoIdentitySignPlcOperation200Response, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            var task = ComAtprotoIdentitySubmitPlcOperationWithHttpInfoAsync(comAtprotoIdentitySignPlcOperation200Response, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            await task.ConfigureAwait(false);
#else
            await task;
#endif
        }

        /// <summary>
        ///  Validates a PLC operation to ensure that it doesn&#39;t violate a service&#39;s constraints or get the identity into a bad state, then submits it to the PLC registry
        /// </summary>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="comAtprotoIdentitySignPlcOperation200Response"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Bluesky.Client.ApiResponse<Object>> ComAtprotoIdentitySubmitPlcOperationWithHttpInfoAsync(ComAtprotoIdentitySignPlcOperation200Response comAtprotoIdentitySignPlcOperation200Response, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'comAtprotoIdentitySignPlcOperation200Response' is set
            if (comAtprotoIdentitySignPlcOperation200Response == null)
                throw new Bluesky.Client.ApiException(400, "Missing required parameter 'comAtprotoIdentitySignPlcOperation200Response' when calling ComAtprotoIdentityApi->ComAtprotoIdentitySubmitPlcOperation");


            Bluesky.Client.RequestOptions localVarRequestOptions = new Bluesky.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Bluesky.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Bluesky.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = comAtprotoIdentitySignPlcOperation200Response;


            // make the HTTP request

            var task = this.AsynchronousClient.PostAsync<Object>("/com.atproto.identity.submitPlcOperation", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ComAtprotoIdentitySubmitPlcOperation", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Updates the current account&#39;s handle. Verifies handle validity, and updates did:plc document if necessary. Implemented by PDS, and requires auth.
        /// </summary>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="comAtprotoIdentityUpdateHandleRequest"></param>
        /// <returns></returns>
        public void ComAtprotoIdentityUpdateHandle(ComAtprotoIdentityUpdateHandleRequest comAtprotoIdentityUpdateHandleRequest)
        {
            ComAtprotoIdentityUpdateHandleWithHttpInfo(comAtprotoIdentityUpdateHandleRequest);
        }

        /// <summary>
        ///  Updates the current account&#39;s handle. Verifies handle validity, and updates did:plc document if necessary. Implemented by PDS, and requires auth.
        /// </summary>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="comAtprotoIdentityUpdateHandleRequest"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Bluesky.Client.ApiResponse<Object> ComAtprotoIdentityUpdateHandleWithHttpInfo(ComAtprotoIdentityUpdateHandleRequest comAtprotoIdentityUpdateHandleRequest)
        {
            // verify the required parameter 'comAtprotoIdentityUpdateHandleRequest' is set
            if (comAtprotoIdentityUpdateHandleRequest == null)
                throw new Bluesky.Client.ApiException(400, "Missing required parameter 'comAtprotoIdentityUpdateHandleRequest' when calling ComAtprotoIdentityApi->ComAtprotoIdentityUpdateHandle");

            Bluesky.Client.RequestOptions localVarRequestOptions = new Bluesky.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Bluesky.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Bluesky.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = comAtprotoIdentityUpdateHandleRequest;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/com.atproto.identity.updateHandle", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ComAtprotoIdentityUpdateHandle", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Updates the current account&#39;s handle. Verifies handle validity, and updates did:plc document if necessary. Implemented by PDS, and requires auth.
        /// </summary>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="comAtprotoIdentityUpdateHandleRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ComAtprotoIdentityUpdateHandleAsync(ComAtprotoIdentityUpdateHandleRequest comAtprotoIdentityUpdateHandleRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            var task = ComAtprotoIdentityUpdateHandleWithHttpInfoAsync(comAtprotoIdentityUpdateHandleRequest, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            await task.ConfigureAwait(false);
#else
            await task;
#endif
        }

        /// <summary>
        ///  Updates the current account&#39;s handle. Verifies handle validity, and updates did:plc document if necessary. Implemented by PDS, and requires auth.
        /// </summary>
        /// <exception cref="Bluesky.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="comAtprotoIdentityUpdateHandleRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Bluesky.Client.ApiResponse<Object>> ComAtprotoIdentityUpdateHandleWithHttpInfoAsync(ComAtprotoIdentityUpdateHandleRequest comAtprotoIdentityUpdateHandleRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'comAtprotoIdentityUpdateHandleRequest' is set
            if (comAtprotoIdentityUpdateHandleRequest == null)
                throw new Bluesky.Client.ApiException(400, "Missing required parameter 'comAtprotoIdentityUpdateHandleRequest' when calling ComAtprotoIdentityApi->ComAtprotoIdentityUpdateHandle");


            Bluesky.Client.RequestOptions localVarRequestOptions = new Bluesky.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Bluesky.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Bluesky.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = comAtprotoIdentityUpdateHandleRequest;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var task = this.AsynchronousClient.PostAsync<Object>("/com.atproto.identity.updateHandle", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ComAtprotoIdentityUpdateHandle", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
