/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Bluesky.Client.OpenAPIDateConverter;

namespace Bluesky.Model
{
    /// <summary>
    /// Metadata about the requesting account&#39;s relationship with the subject content. Only has meaningful content for authed requests.
    /// </summary>
    [DataContract(Name = "app.bsky.feed.defs.viewerState")]
    public partial class AppBskyFeedDefsViewerState
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AppBskyFeedDefsViewerState" /> class.
        /// </summary>
        /// <param name="repost">repost.</param>
        /// <param name="like">like.</param>
        /// <param name="replyDisabled">replyDisabled.</param>
        public AppBskyFeedDefsViewerState(string repost = default(string), string like = default(string), bool replyDisabled = default(bool))
        {
            this.Repost = repost;
            this.Like = like;
            this.ReplyDisabled = replyDisabled;
        }

        /// <summary>
        /// Gets or Sets Repost
        /// </summary>
        [DataMember(Name = "repost", EmitDefaultValue = false)]
        public string Repost { get; set; }

        /// <summary>
        /// Gets or Sets Like
        /// </summary>
        [DataMember(Name = "like", EmitDefaultValue = false)]
        public string Like { get; set; }

        /// <summary>
        /// Gets or Sets ReplyDisabled
        /// </summary>
        [DataMember(Name = "replyDisabled", EmitDefaultValue = true)]
        public bool ReplyDisabled { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AppBskyFeedDefsViewerState {\n");
            sb.Append("  Repost: ").Append(Repost).Append("\n");
            sb.Append("  Like: ").Append(Like).Append("\n");
            sb.Append("  ReplyDisabled: ").Append(ReplyDisabled).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
