/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Bluesky.Client.OpenAPIDateConverter;

namespace Bluesky.Model
{
    /// <summary>
    /// AppBskyFeedDefsSkeletonFeedPost
    /// </summary>
    [DataContract(Name = "app.bsky.feed.defs.skeletonFeedPost")]
    public partial class AppBskyFeedDefsSkeletonFeedPost
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AppBskyFeedDefsSkeletonFeedPost" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AppBskyFeedDefsSkeletonFeedPost() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AppBskyFeedDefsSkeletonFeedPost" /> class.
        /// </summary>
        /// <param name="post">post (required).</param>
        /// <param name="reason">reason.</param>
        public AppBskyFeedDefsSkeletonFeedPost(string post = default(string), AppBskyFeedDefsSkeletonFeedPostReason reason = default(AppBskyFeedDefsSkeletonFeedPostReason))
        {
            // to ensure "post" is required (not null)
            if (post == null)
            {
                throw new ArgumentNullException("post is a required property for AppBskyFeedDefsSkeletonFeedPost and cannot be null");
            }
            this.Post = post;
            this.Reason = reason;
        }

        /// <summary>
        /// Gets or Sets Post
        /// </summary>
        [DataMember(Name = "post", IsRequired = true, EmitDefaultValue = true)]
        public string Post { get; set; }

        /// <summary>
        /// Gets or Sets Reason
        /// </summary>
        [DataMember(Name = "reason", EmitDefaultValue = false)]
        public AppBskyFeedDefsSkeletonFeedPostReason Reason { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AppBskyFeedDefsSkeletonFeedPost {\n");
            sb.Append("  Post: ").Append(Post).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
