/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Bluesky.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Bluesky.Model
{
    /// <summary>
    /// ComAtprotoAdminDefsModEventViewDetailSubject
    /// </summary>
    [JsonConverter(typeof(ComAtprotoAdminDefsModEventViewDetailSubjectJsonConverter))]
    [DataContract(Name = "com_atproto_admin_defs_modEventViewDetail_subject")]
    public partial class ComAtprotoAdminDefsModEventViewDetailSubject : AbstractOpenAPISchema
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ComAtprotoAdminDefsModEventViewDetailSubject" /> class
        /// with the <see cref="ComAtprotoAdminDefsRepoView" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ComAtprotoAdminDefsRepoView.</param>
        public ComAtprotoAdminDefsModEventViewDetailSubject(ComAtprotoAdminDefsRepoView actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ComAtprotoAdminDefsModEventViewDetailSubject" /> class
        /// with the <see cref="ComAtprotoAdminDefsRepoViewNotFound" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ComAtprotoAdminDefsRepoViewNotFound.</param>
        public ComAtprotoAdminDefsModEventViewDetailSubject(ComAtprotoAdminDefsRepoViewNotFound actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ComAtprotoAdminDefsModEventViewDetailSubject" /> class
        /// with the <see cref="ComAtprotoAdminDefsRecordView" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ComAtprotoAdminDefsRecordView.</param>
        public ComAtprotoAdminDefsModEventViewDetailSubject(ComAtprotoAdminDefsRecordView actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ComAtprotoAdminDefsModEventViewDetailSubject" /> class
        /// with the <see cref="ComAtprotoAdminDefsRecordViewNotFound" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ComAtprotoAdminDefsRecordViewNotFound.</param>
        public ComAtprotoAdminDefsModEventViewDetailSubject(ComAtprotoAdminDefsRecordViewNotFound actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(ComAtprotoAdminDefsRecordView))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ComAtprotoAdminDefsRecordViewNotFound))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ComAtprotoAdminDefsRepoView))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ComAtprotoAdminDefsRepoViewNotFound))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: ComAtprotoAdminDefsRecordView, ComAtprotoAdminDefsRecordViewNotFound, ComAtprotoAdminDefsRepoView, ComAtprotoAdminDefsRepoViewNotFound");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `ComAtprotoAdminDefsRepoView`. If the actual instance is not `ComAtprotoAdminDefsRepoView`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ComAtprotoAdminDefsRepoView</returns>
        public ComAtprotoAdminDefsRepoView GetComAtprotoAdminDefsRepoView()
        {
            return (ComAtprotoAdminDefsRepoView)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ComAtprotoAdminDefsRepoViewNotFound`. If the actual instance is not `ComAtprotoAdminDefsRepoViewNotFound`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ComAtprotoAdminDefsRepoViewNotFound</returns>
        public ComAtprotoAdminDefsRepoViewNotFound GetComAtprotoAdminDefsRepoViewNotFound()
        {
            return (ComAtprotoAdminDefsRepoViewNotFound)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ComAtprotoAdminDefsRecordView`. If the actual instance is not `ComAtprotoAdminDefsRecordView`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ComAtprotoAdminDefsRecordView</returns>
        public ComAtprotoAdminDefsRecordView GetComAtprotoAdminDefsRecordView()
        {
            return (ComAtprotoAdminDefsRecordView)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ComAtprotoAdminDefsRecordViewNotFound`. If the actual instance is not `ComAtprotoAdminDefsRecordViewNotFound`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ComAtprotoAdminDefsRecordViewNotFound</returns>
        public ComAtprotoAdminDefsRecordViewNotFound GetComAtprotoAdminDefsRecordViewNotFound()
        {
            return (ComAtprotoAdminDefsRecordViewNotFound)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ComAtprotoAdminDefsModEventViewDetailSubject {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, ComAtprotoAdminDefsModEventViewDetailSubject.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of ComAtprotoAdminDefsModEventViewDetailSubject
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of ComAtprotoAdminDefsModEventViewDetailSubject</returns>
        public static ComAtprotoAdminDefsModEventViewDetailSubject FromJson(string jsonString)
        {
            ComAtprotoAdminDefsModEventViewDetailSubject newComAtprotoAdminDefsModEventViewDetailSubject = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newComAtprotoAdminDefsModEventViewDetailSubject;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ComAtprotoAdminDefsRecordView).GetProperty("AdditionalProperties") == null)
                {
                    newComAtprotoAdminDefsModEventViewDetailSubject = new ComAtprotoAdminDefsModEventViewDetailSubject(JsonConvert.DeserializeObject<ComAtprotoAdminDefsRecordView>(jsonString, ComAtprotoAdminDefsModEventViewDetailSubject.SerializerSettings));
                }
                else
                {
                    newComAtprotoAdminDefsModEventViewDetailSubject = new ComAtprotoAdminDefsModEventViewDetailSubject(JsonConvert.DeserializeObject<ComAtprotoAdminDefsRecordView>(jsonString, ComAtprotoAdminDefsModEventViewDetailSubject.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ComAtprotoAdminDefsRecordView");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ComAtprotoAdminDefsRecordView: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ComAtprotoAdminDefsRecordViewNotFound).GetProperty("AdditionalProperties") == null)
                {
                    newComAtprotoAdminDefsModEventViewDetailSubject = new ComAtprotoAdminDefsModEventViewDetailSubject(JsonConvert.DeserializeObject<ComAtprotoAdminDefsRecordViewNotFound>(jsonString, ComAtprotoAdminDefsModEventViewDetailSubject.SerializerSettings));
                }
                else
                {
                    newComAtprotoAdminDefsModEventViewDetailSubject = new ComAtprotoAdminDefsModEventViewDetailSubject(JsonConvert.DeserializeObject<ComAtprotoAdminDefsRecordViewNotFound>(jsonString, ComAtprotoAdminDefsModEventViewDetailSubject.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ComAtprotoAdminDefsRecordViewNotFound");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ComAtprotoAdminDefsRecordViewNotFound: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ComAtprotoAdminDefsRepoView).GetProperty("AdditionalProperties") == null)
                {
                    newComAtprotoAdminDefsModEventViewDetailSubject = new ComAtprotoAdminDefsModEventViewDetailSubject(JsonConvert.DeserializeObject<ComAtprotoAdminDefsRepoView>(jsonString, ComAtprotoAdminDefsModEventViewDetailSubject.SerializerSettings));
                }
                else
                {
                    newComAtprotoAdminDefsModEventViewDetailSubject = new ComAtprotoAdminDefsModEventViewDetailSubject(JsonConvert.DeserializeObject<ComAtprotoAdminDefsRepoView>(jsonString, ComAtprotoAdminDefsModEventViewDetailSubject.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ComAtprotoAdminDefsRepoView");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ComAtprotoAdminDefsRepoView: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ComAtprotoAdminDefsRepoViewNotFound).GetProperty("AdditionalProperties") == null)
                {
                    newComAtprotoAdminDefsModEventViewDetailSubject = new ComAtprotoAdminDefsModEventViewDetailSubject(JsonConvert.DeserializeObject<ComAtprotoAdminDefsRepoViewNotFound>(jsonString, ComAtprotoAdminDefsModEventViewDetailSubject.SerializerSettings));
                }
                else
                {
                    newComAtprotoAdminDefsModEventViewDetailSubject = new ComAtprotoAdminDefsModEventViewDetailSubject(JsonConvert.DeserializeObject<ComAtprotoAdminDefsRepoViewNotFound>(jsonString, ComAtprotoAdminDefsModEventViewDetailSubject.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ComAtprotoAdminDefsRepoViewNotFound");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ComAtprotoAdminDefsRepoViewNotFound: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newComAtprotoAdminDefsModEventViewDetailSubject;
        }

    }

    /// <summary>
    /// Custom JSON converter for ComAtprotoAdminDefsModEventViewDetailSubject
    /// </summary>
    public class ComAtprotoAdminDefsModEventViewDetailSubjectJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(ComAtprotoAdminDefsModEventViewDetailSubject).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if(reader.TokenType != JsonToken.Null)
            {
                return ComAtprotoAdminDefsModEventViewDetailSubject.FromJson(JObject.Load(reader).ToString(Formatting.None));
            }
            return null;
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
