/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using NUnit.Framework;

using Bluesky.Client;
using Bluesky.Api;
// uncomment below to import models
//using Bluesky.Model;

namespace Bluesky.Test.Api
{
    /// <summary>
    ///  Class for testing AppBskyGraphApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AppBskyGraphApiTests : IDisposable
    {
        private AppBskyGraphApi instance;

        public AppBskyGraphApiTests()
        {
            instance = new AppBskyGraphApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppBskyGraphApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AppBskyGraphApi
            //Assert.IsType<AppBskyGraphApi>(instance);
        }

        /// <summary>
        /// Test AppBskyGraphGetBlocks
        /// </summary>
        [Test]
        public void AppBskyGraphGetBlocksTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //string? cursor = null;
            //var response = instance.AppBskyGraphGetBlocks(limit, cursor);
            //Assert.IsType<AppBskyGraphGetBlocks200Response>(response);
        }

        /// <summary>
        /// Test AppBskyGraphGetFollowers
        /// </summary>
        [Test]
        public void AppBskyGraphGetFollowersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string actor = null;
            //int? limit = null;
            //string? cursor = null;
            //var response = instance.AppBskyGraphGetFollowers(actor, limit, cursor);
            //Assert.IsType<AppBskyGraphGetFollowers200Response>(response);
        }

        /// <summary>
        /// Test AppBskyGraphGetFollows
        /// </summary>
        [Test]
        public void AppBskyGraphGetFollowsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string actor = null;
            //int? limit = null;
            //string? cursor = null;
            //var response = instance.AppBskyGraphGetFollows(actor, limit, cursor);
            //Assert.IsType<AppBskyGraphGetFollows200Response>(response);
        }

        /// <summary>
        /// Test AppBskyGraphGetList
        /// </summary>
        [Test]
        public void AppBskyGraphGetListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string list = null;
            //int? limit = null;
            //string? cursor = null;
            //var response = instance.AppBskyGraphGetList(list, limit, cursor);
            //Assert.IsType<AppBskyGraphGetList200Response>(response);
        }

        /// <summary>
        /// Test AppBskyGraphGetListBlocks
        /// </summary>
        [Test]
        public void AppBskyGraphGetListBlocksTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //string? cursor = null;
            //var response = instance.AppBskyGraphGetListBlocks(limit, cursor);
            //Assert.IsType<AppBskyGraphGetListBlocks200Response>(response);
        }

        /// <summary>
        /// Test AppBskyGraphGetListMutes
        /// </summary>
        [Test]
        public void AppBskyGraphGetListMutesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //string? cursor = null;
            //var response = instance.AppBskyGraphGetListMutes(limit, cursor);
            //Assert.IsType<AppBskyGraphGetListBlocks200Response>(response);
        }

        /// <summary>
        /// Test AppBskyGraphGetLists
        /// </summary>
        [Test]
        public void AppBskyGraphGetListsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string actor = null;
            //int? limit = null;
            //string? cursor = null;
            //var response = instance.AppBskyGraphGetLists(actor, limit, cursor);
            //Assert.IsType<AppBskyGraphGetListBlocks200Response>(response);
        }

        /// <summary>
        /// Test AppBskyGraphGetMutes
        /// </summary>
        [Test]
        public void AppBskyGraphGetMutesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //string? cursor = null;
            //var response = instance.AppBskyGraphGetMutes(limit, cursor);
            //Assert.IsType<AppBskyGraphGetMutes200Response>(response);
        }

        /// <summary>
        /// Test AppBskyGraphGetSuggestedFollowsByActor
        /// </summary>
        [Test]
        public void AppBskyGraphGetSuggestedFollowsByActorTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string actor = null;
            //var response = instance.AppBskyGraphGetSuggestedFollowsByActor(actor);
            //Assert.IsType<AppBskyGraphGetSuggestedFollowsByActor200Response>(response);
        }

        /// <summary>
        /// Test AppBskyGraphMuteActor
        /// </summary>
        [Test]
        public void AppBskyGraphMuteActorTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AppBskyGraphMuteActorRequest appBskyGraphMuteActorRequest = null;
            //instance.AppBskyGraphMuteActor(appBskyGraphMuteActorRequest);
        }

        /// <summary>
        /// Test AppBskyGraphMuteActorList
        /// </summary>
        [Test]
        public void AppBskyGraphMuteActorListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AppBskyGraphMuteActorListRequest appBskyGraphMuteActorListRequest = null;
            //instance.AppBskyGraphMuteActorList(appBskyGraphMuteActorListRequest);
        }

        /// <summary>
        /// Test AppBskyGraphUnmuteActor
        /// </summary>
        [Test]
        public void AppBskyGraphUnmuteActorTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AppBskyGraphMuteActorRequest appBskyGraphMuteActorRequest = null;
            //instance.AppBskyGraphUnmuteActor(appBskyGraphMuteActorRequest);
        }

        /// <summary>
        /// Test AppBskyGraphUnmuteActorList
        /// </summary>
        [Test]
        public void AppBskyGraphUnmuteActorListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AppBskyGraphMuteActorListRequest appBskyGraphMuteActorListRequest = null;
            //instance.AppBskyGraphUnmuteActorList(appBskyGraphMuteActorListRequest);
        }
    }
}
