/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bluesky.Api;
using Bluesky.Model;
using Bluesky.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Bluesky.Test.Model
{
    /// <summary>
    ///  Class for testing AppBskyActorGetProfiles200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AppBskyActorGetProfiles200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AppBskyActorGetProfiles200Response
        //private AppBskyActorGetProfiles200Response instance;

        public AppBskyActorGetProfiles200ResponseTests()
        {
            // TODO uncomment below to create an instance of AppBskyActorGetProfiles200Response
            //instance = new AppBskyActorGetProfiles200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppBskyActorGetProfiles200Response
        /// </summary>
        [Test]
        public void AppBskyActorGetProfiles200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AppBskyActorGetProfiles200Response
            //Assert.IsType<AppBskyActorGetProfiles200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Profiles'
        /// </summary>
        [Test]
        public void ProfilesTest()
        {
            // TODO unit test for the property 'Profiles'
        }
    }
}
