/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bluesky.Api;
using Bluesky.Model;
using Bluesky.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Bluesky.Test.Model
{
    /// <summary>
    ///  Class for testing AppBskyEmbedRecord
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AppBskyEmbedRecordTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AppBskyEmbedRecord
        //private AppBskyEmbedRecord instance;

        public AppBskyEmbedRecordTests()
        {
            // TODO uncomment below to create an instance of AppBskyEmbedRecord
            //instance = new AppBskyEmbedRecord();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppBskyEmbedRecord
        /// </summary>
        [Test]
        public void AppBskyEmbedRecordInstanceTest()
        {
            // TODO uncomment below to test "IsType" AppBskyEmbedRecord
            //Assert.IsType<AppBskyEmbedRecord>(instance);
        }

        /// <summary>
        /// Test the property 'Record'
        /// </summary>
        [Test]
        public void RecordTest()
        {
            // TODO unit test for the property 'Record'
        }
    }
}
