/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bluesky.Api;
using Bluesky.Model;
using Bluesky.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Bluesky.Test.Model
{
    /// <summary>
    ///  Class for testing AppBskyGraphDefsListViewBasic
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AppBskyGraphDefsListViewBasicTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AppBskyGraphDefsListViewBasic
        //private AppBskyGraphDefsListViewBasic instance;

        public AppBskyGraphDefsListViewBasicTests()
        {
            // TODO uncomment below to create an instance of AppBskyGraphDefsListViewBasic
            //instance = new AppBskyGraphDefsListViewBasic();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppBskyGraphDefsListViewBasic
        /// </summary>
        [Test]
        public void AppBskyGraphDefsListViewBasicInstanceTest()
        {
            // TODO uncomment below to test "IsType" AppBskyGraphDefsListViewBasic
            //Assert.IsType<AppBskyGraphDefsListViewBasic>(instance);
        }

        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Test]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }
        /// <summary>
        /// Test the property 'Cid'
        /// </summary>
        [Test]
        public void CidTest()
        {
            // TODO unit test for the property 'Cid'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Purpose'
        /// </summary>
        [Test]
        public void PurposeTest()
        {
            // TODO unit test for the property 'Purpose'
        }
        /// <summary>
        /// Test the property 'Avatar'
        /// </summary>
        [Test]
        public void AvatarTest()
        {
            // TODO unit test for the property 'Avatar'
        }
        /// <summary>
        /// Test the property 'Viewer'
        /// </summary>
        [Test]
        public void ViewerTest()
        {
            // TODO unit test for the property 'Viewer'
        }
        /// <summary>
        /// Test the property 'IndexedAt'
        /// </summary>
        [Test]
        public void IndexedAtTest()
        {
            // TODO unit test for the property 'IndexedAt'
        }
    }
}
