/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bluesky.Api;
using Bluesky.Model;
using Bluesky.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Bluesky.Test.Model
{
    /// <summary>
    ///  Class for testing AppBskyFeedDefsViewerState
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AppBskyFeedDefsViewerStateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AppBskyFeedDefsViewerState
        //private AppBskyFeedDefsViewerState instance;

        public AppBskyFeedDefsViewerStateTests()
        {
            // TODO uncomment below to create an instance of AppBskyFeedDefsViewerState
            //instance = new AppBskyFeedDefsViewerState();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppBskyFeedDefsViewerState
        /// </summary>
        [Test]
        public void AppBskyFeedDefsViewerStateInstanceTest()
        {
            // TODO uncomment below to test "IsType" AppBskyFeedDefsViewerState
            //Assert.IsType<AppBskyFeedDefsViewerState>(instance);
        }

        /// <summary>
        /// Test the property 'Repost'
        /// </summary>
        [Test]
        public void RepostTest()
        {
            // TODO unit test for the property 'Repost'
        }
        /// <summary>
        /// Test the property 'Like'
        /// </summary>
        [Test]
        public void LikeTest()
        {
            // TODO unit test for the property 'Like'
        }
        /// <summary>
        /// Test the property 'ReplyDisabled'
        /// </summary>
        [Test]
        public void ReplyDisabledTest()
        {
            // TODO unit test for the property 'ReplyDisabled'
        }
    }
}
