/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bluesky.Api;
using Bluesky.Model;
using Bluesky.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Bluesky.Test.Model
{
    /// <summary>
    ///  Class for testing AppBskyFeedGetFeedGenerator200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AppBskyFeedGetFeedGenerator200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AppBskyFeedGetFeedGenerator200Response
        //private AppBskyFeedGetFeedGenerator200Response instance;

        public AppBskyFeedGetFeedGenerator200ResponseTests()
        {
            // TODO uncomment below to create an instance of AppBskyFeedGetFeedGenerator200Response
            //instance = new AppBskyFeedGetFeedGenerator200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppBskyFeedGetFeedGenerator200Response
        /// </summary>
        [Test]
        public void AppBskyFeedGetFeedGenerator200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AppBskyFeedGetFeedGenerator200Response
            //Assert.IsType<AppBskyFeedGetFeedGenerator200Response>(instance);
        }

        /// <summary>
        /// Test the property 'View'
        /// </summary>
        [Test]
        public void ViewTest()
        {
            // TODO unit test for the property 'View'
        }
        /// <summary>
        /// Test the property 'IsOnline'
        /// </summary>
        [Test]
        public void IsOnlineTest()
        {
            // TODO unit test for the property 'IsOnline'
        }
        /// <summary>
        /// Test the property 'IsValid'
        /// </summary>
        [Test]
        public void IsValidTest()
        {
            // TODO unit test for the property 'IsValid'
        }
    }
}
