/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bluesky.Api;
using Bluesky.Model;
using Bluesky.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Bluesky.Test.Model
{
    /// <summary>
    ///  Class for testing ComAtprotoServerUpdateEmail400Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ComAtprotoServerUpdateEmail400ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ComAtprotoServerUpdateEmail400Response
        //private ComAtprotoServerUpdateEmail400Response instance;

        public ComAtprotoServerUpdateEmail400ResponseTests()
        {
            // TODO uncomment below to create an instance of ComAtprotoServerUpdateEmail400Response
            //instance = new ComAtprotoServerUpdateEmail400Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ComAtprotoServerUpdateEmail400Response
        /// </summary>
        [Test]
        public void ComAtprotoServerUpdateEmail400ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ComAtprotoServerUpdateEmail400Response
            //Assert.IsType<ComAtprotoServerUpdateEmail400Response>(instance);
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Test]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
