/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bluesky.Api;
using Bluesky.Model;
using Bluesky.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Bluesky.Test.Model
{
    /// <summary>
    ///  Class for testing ComAtprotoSyncSubscribeReposMigrate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ComAtprotoSyncSubscribeReposMigrateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ComAtprotoSyncSubscribeReposMigrate
        //private ComAtprotoSyncSubscribeReposMigrate instance;

        public ComAtprotoSyncSubscribeReposMigrateTests()
        {
            // TODO uncomment below to create an instance of ComAtprotoSyncSubscribeReposMigrate
            //instance = new ComAtprotoSyncSubscribeReposMigrate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ComAtprotoSyncSubscribeReposMigrate
        /// </summary>
        [Test]
        public void ComAtprotoSyncSubscribeReposMigrateInstanceTest()
        {
            // TODO uncomment below to test "IsType" ComAtprotoSyncSubscribeReposMigrate
            //Assert.IsType<ComAtprotoSyncSubscribeReposMigrate>(instance);
        }

        /// <summary>
        /// Test the property 'Seq'
        /// </summary>
        [Test]
        public void SeqTest()
        {
            // TODO unit test for the property 'Seq'
        }
        /// <summary>
        /// Test the property 'Did'
        /// </summary>
        [Test]
        public void DidTest()
        {
            // TODO unit test for the property 'Did'
        }
        /// <summary>
        /// Test the property 'MigrateTo'
        /// </summary>
        [Test]
        public void MigrateToTest()
        {
            // TODO unit test for the property 'MigrateTo'
        }
        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Test]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }
    }
}
