/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bluesky.Api;
using Bluesky.Model;
using Bluesky.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Bluesky.Test.Model
{
    /// <summary>
    ///  Class for testing ComAtprotoAdminUpdateCommunicationTemplateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ComAtprotoAdminUpdateCommunicationTemplateRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ComAtprotoAdminUpdateCommunicationTemplateRequest
        //private ComAtprotoAdminUpdateCommunicationTemplateRequest instance;

        public ComAtprotoAdminUpdateCommunicationTemplateRequestTests()
        {
            // TODO uncomment below to create an instance of ComAtprotoAdminUpdateCommunicationTemplateRequest
            //instance = new ComAtprotoAdminUpdateCommunicationTemplateRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ComAtprotoAdminUpdateCommunicationTemplateRequest
        /// </summary>
        [Test]
        public void ComAtprotoAdminUpdateCommunicationTemplateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ComAtprotoAdminUpdateCommunicationTemplateRequest
            //Assert.IsType<ComAtprotoAdminUpdateCommunicationTemplateRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ContentMarkdown'
        /// </summary>
        [Test]
        public void ContentMarkdownTest()
        {
            // TODO unit test for the property 'ContentMarkdown'
        }
        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Test]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
        /// <summary>
        /// Test the property 'UpdatedBy'
        /// </summary>
        [Test]
        public void UpdatedByTest()
        {
            // TODO unit test for the property 'UpdatedBy'
        }
        /// <summary>
        /// Test the property 'Disabled'
        /// </summary>
        [Test]
        public void DisabledTest()
        {
            // TODO unit test for the property 'Disabled'
        }
    }
}
