/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bluesky.Api;
using Bluesky.Model;
using Bluesky.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Bluesky.Test.Model
{
    /// <summary>
    ///  Class for testing ComAtprotoAdminDefsVideoDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ComAtprotoAdminDefsVideoDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ComAtprotoAdminDefsVideoDetails
        //private ComAtprotoAdminDefsVideoDetails instance;

        public ComAtprotoAdminDefsVideoDetailsTests()
        {
            // TODO uncomment below to create an instance of ComAtprotoAdminDefsVideoDetails
            //instance = new ComAtprotoAdminDefsVideoDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ComAtprotoAdminDefsVideoDetails
        /// </summary>
        [Test]
        public void ComAtprotoAdminDefsVideoDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ComAtprotoAdminDefsVideoDetails
            //Assert.IsType<ComAtprotoAdminDefsVideoDetails>(instance);
        }

        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Test]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }
        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Test]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }
        /// <summary>
        /// Test the property 'Length'
        /// </summary>
        [Test]
        public void LengthTest()
        {
            // TODO unit test for the property 'Length'
        }
    }
}
