/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bluesky.Api;
using Bluesky.Model;
using Bluesky.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Bluesky.Test.Model
{
    /// <summary>
    ///  Class for testing ComAtprotoRepoApplyWritesRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ComAtprotoRepoApplyWritesRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ComAtprotoRepoApplyWritesRequest
        //private ComAtprotoRepoApplyWritesRequest instance;

        public ComAtprotoRepoApplyWritesRequestTests()
        {
            // TODO uncomment below to create an instance of ComAtprotoRepoApplyWritesRequest
            //instance = new ComAtprotoRepoApplyWritesRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ComAtprotoRepoApplyWritesRequest
        /// </summary>
        [Test]
        public void ComAtprotoRepoApplyWritesRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ComAtprotoRepoApplyWritesRequest
            //Assert.IsType<ComAtprotoRepoApplyWritesRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Repo'
        /// </summary>
        [Test]
        public void RepoTest()
        {
            // TODO unit test for the property 'Repo'
        }
        /// <summary>
        /// Test the property 'Validate'
        /// </summary>
        [Test]
        public void ValidateTest()
        {
            // TODO unit test for the property 'Validate'
        }
        /// <summary>
        /// Test the property 'Writes'
        /// </summary>
        [Test]
        public void WritesTest()
        {
            // TODO unit test for the property 'Writes'
        }
        /// <summary>
        /// Test the property 'SwapCommit'
        /// </summary>
        [Test]
        public void SwapCommitTest()
        {
            // TODO unit test for the property 'SwapCommit'
        }
    }
}
