/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bluesky.Api;
using Bluesky.Model;
using Bluesky.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Bluesky.Test.Model
{
    /// <summary>
    ///  Class for testing ComAtprotoAdminEmitModerationEventRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ComAtprotoAdminEmitModerationEventRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ComAtprotoAdminEmitModerationEventRequest
        //private ComAtprotoAdminEmitModerationEventRequest instance;

        public ComAtprotoAdminEmitModerationEventRequestTests()
        {
            // TODO uncomment below to create an instance of ComAtprotoAdminEmitModerationEventRequest
            //instance = new ComAtprotoAdminEmitModerationEventRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ComAtprotoAdminEmitModerationEventRequest
        /// </summary>
        [Test]
        public void ComAtprotoAdminEmitModerationEventRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ComAtprotoAdminEmitModerationEventRequest
            //Assert.IsType<ComAtprotoAdminEmitModerationEventRequest>(instance);
        }

        /// <summary>
        /// Test the property 'VarEvent'
        /// </summary>
        [Test]
        public void VarEventTest()
        {
            // TODO unit test for the property 'VarEvent'
        }
        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Test]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
        /// <summary>
        /// Test the property 'SubjectBlobCids'
        /// </summary>
        [Test]
        public void SubjectBlobCidsTest()
        {
            // TODO unit test for the property 'SubjectBlobCids'
        }
        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Test]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }
    }
}
