/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bluesky.Api;
using Bluesky.Model;
using Bluesky.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Bluesky.Test.Model
{
    /// <summary>
    ///  Class for testing ComAtprotoAdminSearchRepos200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ComAtprotoAdminSearchRepos200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ComAtprotoAdminSearchRepos200Response
        //private ComAtprotoAdminSearchRepos200Response instance;

        public ComAtprotoAdminSearchRepos200ResponseTests()
        {
            // TODO uncomment below to create an instance of ComAtprotoAdminSearchRepos200Response
            //instance = new ComAtprotoAdminSearchRepos200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ComAtprotoAdminSearchRepos200Response
        /// </summary>
        [Test]
        public void ComAtprotoAdminSearchRepos200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ComAtprotoAdminSearchRepos200Response
            //Assert.IsType<ComAtprotoAdminSearchRepos200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Cursor'
        /// </summary>
        [Test]
        public void CursorTest()
        {
            // TODO unit test for the property 'Cursor'
        }
        /// <summary>
        /// Test the property 'Repos'
        /// </summary>
        [Test]
        public void ReposTest()
        {
            // TODO unit test for the property 'Repos'
        }
    }
}
