/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bluesky.Api;
using Bluesky.Model;
using Bluesky.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Bluesky.Test.Model
{
    /// <summary>
    ///  Class for testing ComAtprotoAdminDefsModEventLabel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ComAtprotoAdminDefsModEventLabelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ComAtprotoAdminDefsModEventLabel
        //private ComAtprotoAdminDefsModEventLabel instance;

        public ComAtprotoAdminDefsModEventLabelTests()
        {
            // TODO uncomment below to create an instance of ComAtprotoAdminDefsModEventLabel
            //instance = new ComAtprotoAdminDefsModEventLabel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ComAtprotoAdminDefsModEventLabel
        /// </summary>
        [Test]
        public void ComAtprotoAdminDefsModEventLabelInstanceTest()
        {
            // TODO uncomment below to test "IsType" ComAtprotoAdminDefsModEventLabel
            //Assert.IsType<ComAtprotoAdminDefsModEventLabel>(instance);
        }

        /// <summary>
        /// Test the property 'Comment'
        /// </summary>
        [Test]
        public void CommentTest()
        {
            // TODO unit test for the property 'Comment'
        }
        /// <summary>
        /// Test the property 'CreateLabelVals'
        /// </summary>
        [Test]
        public void CreateLabelValsTest()
        {
            // TODO unit test for the property 'CreateLabelVals'
        }
        /// <summary>
        /// Test the property 'NegateLabelVals'
        /// </summary>
        [Test]
        public void NegateLabelValsTest()
        {
            // TODO unit test for the property 'NegateLabelVals'
        }
    }
}
