/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bluesky.Api;
using Bluesky.Model;
using Bluesky.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Bluesky.Test.Model
{
    /// <summary>
    ///  Class for testing ComAtprotoAdminDefsBlobView
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ComAtprotoAdminDefsBlobViewTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ComAtprotoAdminDefsBlobView
        //private ComAtprotoAdminDefsBlobView instance;

        public ComAtprotoAdminDefsBlobViewTests()
        {
            // TODO uncomment below to create an instance of ComAtprotoAdminDefsBlobView
            //instance = new ComAtprotoAdminDefsBlobView();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ComAtprotoAdminDefsBlobView
        /// </summary>
        [Test]
        public void ComAtprotoAdminDefsBlobViewInstanceTest()
        {
            // TODO uncomment below to test "IsType" ComAtprotoAdminDefsBlobView
            //Assert.IsType<ComAtprotoAdminDefsBlobView>(instance);
        }

        /// <summary>
        /// Test the property 'Cid'
        /// </summary>
        [Test]
        public void CidTest()
        {
            // TODO unit test for the property 'Cid'
        }
        /// <summary>
        /// Test the property 'MimeType'
        /// </summary>
        [Test]
        public void MimeTypeTest()
        {
            // TODO unit test for the property 'MimeType'
        }
        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Test]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'Details'
        /// </summary>
        [Test]
        public void DetailsTest()
        {
            // TODO unit test for the property 'Details'
        }
        /// <summary>
        /// Test the property 'Moderation'
        /// </summary>
        [Test]
        public void ModerationTest()
        {
            // TODO unit test for the property 'Moderation'
        }
    }
}
